-- ==============================================
-- SKENARIO 6: N=100, V=50, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_001', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_002', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_003', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_006', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_007', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_008', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_009', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_011', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_012', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_013', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_015', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_017', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_018', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_020', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_021', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_022', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_023', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_024', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_025', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_027', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_028', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_033', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_034', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_035', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_036', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_037', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_040', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_041', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_042', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_043', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_044', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_045', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_046', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_047', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_048', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_050', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_051', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_052', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_053', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_054', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_055', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_056', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_057', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_058', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_059', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_060', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_061', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_062', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_063', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_064', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_065', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_066', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_067', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_068', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_070', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_072', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_073', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_074', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_075', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_076', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_077', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_079', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_080', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_081', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_083', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_084', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_085', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_086', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_087', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_089', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_090', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_091', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_092', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_094', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_095', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_096', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_097', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_098', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_099', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS6_100', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS6_001', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS6_002', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS6_003', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS6_004', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS6_005', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS6_006', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS6_007', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS6_008', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS6_009', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS6_010', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS6_011', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS6_012', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS6_013', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS6_014', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS6_015', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS6_016', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS6_017', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS6_018', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS6_019', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS6_020', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS6_021', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS6_022', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS6_023', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS6_024', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS6_025', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS6_026', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS6_027', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS6_028', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS6_029', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS6_030', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS6_031', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS6_032', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS6_033', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS6_034', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS6_035', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS6_036', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS6_037', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS6_038', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS6_039', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS6_040', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS6_041', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS6_042', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS6_043', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS6_044', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS6_045', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS6_046', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS6_047', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS6_048', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS6_049', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS6_050', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS6_051', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS6_052', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS6_053', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS6_054', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS6_055', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS6_056', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS6_057', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS6_058', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS6_059', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS6_060', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS6_061', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS6_062', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS6_063', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS6_064', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS6_065', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS6_066', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS6_067', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS6_068', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS6_069', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS6_070', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS6_071', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS6_072', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS6_073', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS6_074', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS6_075', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS6_076', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS6_077', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS6_078', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS6_079', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS6_080', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS6_081', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS6_082', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS6_083', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS6_084', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS6_085', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS6_086', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS6_087', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS6_088', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS6_089', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS6_090', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS6_091', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS6_092', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS6_093', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS6_094', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS6_095', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS6_096', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS6_097', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS6_098', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS6_099', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS6_100', 10);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS6_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS6_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS6_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS6_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS6_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS6_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS6_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS6_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS6_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS6_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS6_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS6_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS6_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS6_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS6_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS6_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS6_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS6_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS6_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS6_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS6_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS6_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS6_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS6_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS6_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS6_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS6_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS6_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS6_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS6_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS6_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS6_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS6_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS6_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS6_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS6_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS6_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS6_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS6_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS6_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS6_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS6_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS6_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS6_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS6_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS6_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS6_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS6_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS6_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS6_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS6_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS6_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS6_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS6_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS6_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS6_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS6_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS6_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS6_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS6_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS6_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS6_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS6_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS6_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS6_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS6_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS6_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS6_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS6_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS6_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS6_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS6_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS6_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS6_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS6_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS6_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS6_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS6_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS6_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS6_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS6_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS6_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS6_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS6_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS6_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS6_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS6_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS6_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS6_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS6_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS6_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS6_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS6_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS6_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS6_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS6_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS6_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS6_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS6_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS6_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS021');


