-- ==============================================
-- SKENARIO 14: N=40, V=50, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_001', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_002', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_003', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_005', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_006', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_007', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_008', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_009', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_012', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_013', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_015', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_016', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_017', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_018', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_021', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_022', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_023', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_024', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_025', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_027', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_028', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_029', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_030', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_034', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_036', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_037', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_038', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_039', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS14_040', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS14_001', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS14_002', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS14_003', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS14_004', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS14_005', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS14_006', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS14_007', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS14_008', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS14_009', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS14_010', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS14_011', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS14_012', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS14_013', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS14_014', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS14_015', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS14_016', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS14_017', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS14_018', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS14_019', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS14_020', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS14_021', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS14_022', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS14_023', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS14_024', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS14_025', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS14_026', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS14_027', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS14_028', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS14_029', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS14_030', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS14_031', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS14_032', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS14_033', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS14_034', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS14_035', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS14_036', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS14_037', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS14_038', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS14_039', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS14_040', 4);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS14_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS14_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS14_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS14_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS14_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS14_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS14_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS14_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS14_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS14_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS14_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS14_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS14_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS14_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS14_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS14_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS14_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS14_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS14_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS14_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS14_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS14_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS14_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS14_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS14_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS14_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS14_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS14_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS14_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS14_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS14_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS14_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS14_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS14_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS14_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS14_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS14_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS14_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS14_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS14_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS040');


