-- ==============================================
-- SKENARIO 3: N=100, V=20, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_001', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_002', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_003', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_004', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_005', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_006', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_007', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_008', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_009', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_010', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_011', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_012', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_013', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_014', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_015', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_016', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_017', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_018', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_020', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_021', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_022', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_024', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_025', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_027', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_028', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_029', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_031', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_034', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_036', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_040', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_041', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_042', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_044', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_046', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_047', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_048', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_050', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_051', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_052', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_053', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_054', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_056', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_057', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_058', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_059', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_060', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_061', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_062', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_063', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_064', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_065', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_066', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_067', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_070', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_072', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_073', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_074', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_075', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_076', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_077', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_079', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_080', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_084', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_085', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_086', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_087', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_089', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_090', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_091', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_092', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_094', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_095', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_096', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_097', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_098', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_099', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS3_100', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS3_001', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS3_002', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS3_003', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS3_004', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS3_005', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS3_006', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS3_007', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS3_008', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS3_009', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS3_010', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS3_011', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS3_012', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS3_013', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS3_014', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS3_015', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS3_016', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS3_017', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS3_018', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS3_019', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS3_020', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS3_021', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS3_022', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS3_023', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS3_024', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS3_025', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS3_026', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS3_027', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS3_028', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS3_029', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS3_030', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS3_031', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS3_032', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS3_033', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS3_034', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS3_035', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS3_036', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS3_037', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS3_038', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS3_039', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS3_040', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS3_041', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS3_042', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS3_043', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS3_044', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS3_045', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS3_046', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS3_047', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS3_048', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS3_049', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS3_050', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS3_051', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS3_052', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS3_053', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS3_054', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS3_055', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS3_056', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS3_057', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS3_058', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS3_059', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS3_060', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS3_061', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS3_062', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS3_063', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS3_064', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS3_065', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS3_066', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS3_067', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS3_068', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS3_069', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS3_070', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS3_071', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS3_072', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS3_073', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS3_074', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS3_075', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS3_076', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS3_077', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS3_078', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS3_079', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS3_080', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS3_081', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS3_082', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS3_083', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS3_084', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS3_085', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS3_086', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS3_087', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS3_088', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS3_089', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS3_090', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS3_091', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS3_092', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS3_093', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS3_094', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS3_095', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS3_096', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS3_097', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS3_098', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS3_099', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS3_100', 1);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS3_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS3_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS3_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS3_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS3_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS3_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS3_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS3_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS3_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS3_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS3_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS3_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS3_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS3_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS3_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS3_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS3_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS3_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS3_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS3_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS3_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS3_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS3_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS3_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS3_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS3_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS3_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS3_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS3_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS3_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS3_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS3_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS3_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS3_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS3_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS3_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS3_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS3_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS3_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS3_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS3_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS3_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS3_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS3_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS3_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS3_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS3_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS3_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS3_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS3_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS3_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS3_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS3_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS3_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS3_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS3_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS3_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS3_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS3_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS3_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS3_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS3_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS3_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS3_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS3_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS3_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS3_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS3_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS3_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS3_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS3_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS3_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS3_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS3_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS3_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS3_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS3_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS3_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS3_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS3_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS3_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS3_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS3_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS3_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS3_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS3_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS3_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS3_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS3_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS3_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS3_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS3_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS3_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS3_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS3_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS3_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS3_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS3_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS3_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS3_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS006');


