-- ==============================================
-- SKENARIO 4: N=100, V=30, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_001', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_002', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_003', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_006', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_007', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_008', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_009', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_011', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_012', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_013', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_015', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_017', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_018', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_020', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_021', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_022', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_024', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_025', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_026', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_027', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_028', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_031', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_033', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_034', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_036', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_037', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_038', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_040', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_041', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_042', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_044', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_046', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_047', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_048', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_049', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_050', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_051', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_052', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_053', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_054', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_056', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_057', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_058', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_059', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_060', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_061', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_062', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_063', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_064', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_065', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_066', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_067', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_069', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_070', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_071', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_072', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_073', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_074', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_075', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_076', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_077', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_079', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_080', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_081', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_082', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_083', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_085', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_086', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_087', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_088', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_089', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_090', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_091', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_092', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_093', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_094', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_095', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_096', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_097', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_099', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS4_100', 'Informatika', 2022, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS4_001', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS4_002', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS4_003', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS4_004', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS4_005', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS4_006', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS4_007', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS4_008', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS4_009', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS4_010', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS4_011', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS4_012', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS4_013', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS4_014', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS4_015', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS4_016', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS4_017', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS4_018', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS4_019', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS4_020', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS4_021', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS4_022', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS4_023', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS4_024', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS4_025', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS4_026', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS4_027', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS4_028', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS4_029', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS4_030', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS4_031', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS4_032', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS4_033', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS4_034', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS4_035', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS4_036', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS4_037', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS4_038', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS4_039', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS4_040', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS4_041', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS4_042', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS4_043', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS4_044', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS4_045', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS4_046', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS4_047', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS4_048', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS4_049', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS4_050', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS4_051', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS4_052', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS4_053', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS4_054', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS4_055', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS4_056', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS4_057', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS4_058', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS4_059', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS4_060', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS4_061', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS4_062', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS4_063', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS4_064', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS4_065', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS4_066', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS4_067', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS4_068', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS4_069', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS4_070', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS4_071', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS4_072', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS4_073', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS4_074', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS4_075', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS4_076', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS4_077', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS4_078', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS4_079', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS4_080', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS4_081', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS4_082', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS4_083', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS4_084', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS4_085', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS4_086', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS4_087', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS4_088', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS4_089', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS4_090', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS4_091', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS4_092', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS4_093', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS4_094', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS4_095', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS4_096', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS4_097', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS4_098', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS4_099', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS4_100', 2);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS4_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS4_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS4_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS4_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS4_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS4_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS4_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS4_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS4_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS4_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS4_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS4_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS4_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS4_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS4_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS4_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS4_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS4_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS4_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS4_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS4_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS4_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS4_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS4_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS4_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS4_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS4_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS4_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS4_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS4_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS4_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS4_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS4_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS4_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS4_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS4_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS4_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS4_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS4_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS4_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS4_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS4_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS4_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS4_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS4_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS4_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS4_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS4_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS4_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS4_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS4_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS4_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS4_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS4_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS4_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS4_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS4_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS4_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS4_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS4_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS4_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS4_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS4_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS4_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS4_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS4_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS4_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS4_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS4_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS4_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS4_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS4_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS4_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS4_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS4_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS4_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS4_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS4_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS4_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS4_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS4_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS4_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS4_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS4_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS4_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS4_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS4_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS4_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS4_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS4_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS4_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS4_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS4_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS4_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS4_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS4_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS4_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS4_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS4_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS4_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS021');


