-- ==============================================
-- SKENARIO 1: N=100, V=5, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_001', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_002', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_003', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_004', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_006', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_007', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_008', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_009', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_012', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_013', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_015', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_016', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_017', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_018', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_019', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_021', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_022', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_024', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_025', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_026', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_027', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_028', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_029', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_031', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_034', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_035', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_036', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_037', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_038', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_040', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_041', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_042', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_044', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_045', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_046', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_047', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_048', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_049', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_050', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_051', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_052', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_053', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_054', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_056', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_057', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_058', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_059', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_060', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_061', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_062', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_063', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_064', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_065', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_066', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_067', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_070', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_071', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_072', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_073', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_074', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_075', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_076', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_077', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_079', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_080', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_081', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_083', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_085', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_086', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_087', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_088', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_089', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_090', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_091', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_092', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_094', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_095', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_096', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_097', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_099', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS1_100', 'Informatika', 2023, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS1_001', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS1_002', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS1_003', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS1_004', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS1_005', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS1_006', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS1_007', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS1_008', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS1_009', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS1_010', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS1_011', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS1_012', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS1_013', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS1_014', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS1_015', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS1_016', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS1_017', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS1_018', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS1_019', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS1_020', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS1_021', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS1_022', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS1_023', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS1_024', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS1_025', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS1_026', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS1_027', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS1_028', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS1_029', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS1_030', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS1_031', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS1_032', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS1_033', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS1_034', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS1_035', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS1_036', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS1_037', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS1_038', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS1_039', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS1_040', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS1_041', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS1_042', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS1_043', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS1_044', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS1_045', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS1_046', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS1_047', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS1_048', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS1_049', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS1_050', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS1_051', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS1_052', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS1_053', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS1_054', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS1_055', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS1_056', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS1_057', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS1_058', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS1_059', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS1_060', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS1_061', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS1_062', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS1_063', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS1_064', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS1_065', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS1_066', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS1_067', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS1_068', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS1_069', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS1_070', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS1_071', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS1_072', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS1_073', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS1_074', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS1_075', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS1_076', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS1_077', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS1_078', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS1_079', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS1_080', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS1_081', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS1_082', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS1_083', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS1_084', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS1_085', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS1_086', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS1_087', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS1_088', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS1_089', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS1_090', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS1_091', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS1_092', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS1_093', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS1_094', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS1_095', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS1_096', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS1_097', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS1_098', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS1_099', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS1_100', 3);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS1_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS1_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS1_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS1_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS1_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS1_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS1_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS1_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS1_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS1_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS1_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS1_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS1_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS1_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS1_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS1_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS1_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS1_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS1_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS1_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS1_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS1_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS1_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS1_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS1_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS1_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS1_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS1_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS1_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS1_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS1_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS1_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS1_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS1_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS1_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS1_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS1_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS1_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS1_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS1_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS1_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS1_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS1_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS1_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS1_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS1_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS1_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS1_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS1_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS1_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS1_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS1_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS1_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS1_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS1_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS1_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS1_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS1_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS1_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS1_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS1_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS1_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS1_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS1_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS1_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS1_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS1_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS1_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS1_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS1_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS1_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS1_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS1_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS1_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS1_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS1_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS1_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS1_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS1_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS1_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS1_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS1_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS1_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS1_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS1_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS1_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS1_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS1_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS1_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS1_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS1_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS1_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS1_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS1_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS1_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS1_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS1_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS1_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS1_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS1_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS001');


