-- ==============================================
-- SKENARIO 25: N=100, V=50, P=5
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_001', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_002', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_003', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_005', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_006', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_007', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_008', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_009', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_010', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_011', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_012', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_013', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_015', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_017', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_018', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_019', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_020', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_021', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_022', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_023', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_024', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_025', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_027', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_028', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_029', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_030', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_032', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_034', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_035', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_036', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_038', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_040', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_041', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_042', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_043', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_044', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_045', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_046', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_047', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_048', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_050', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_051', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_052', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_053', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_054', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_055', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_056', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_057', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_058', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_059', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_060', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_061', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_062', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_063', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_064', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_065', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_066', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_067', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_068', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_070', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_071', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_072', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_073', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_074', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_075', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_076', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_077', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_078', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_079', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_080', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_084', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_085', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_086', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_087', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_088', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_089', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_090', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_091', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_092', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_094', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_095', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_096', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_097', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_099', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS25_100', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS25_001', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS25_002', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS25_003', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS25_004', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS25_005', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS25_006', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS25_007', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS25_008', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS25_009', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS25_010', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS25_011', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS25_012', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS25_013', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS25_014', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS25_015', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS25_016', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS25_017', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS25_018', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS25_019', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS25_020', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS25_021', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS25_022', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS25_023', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS25_024', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS25_025', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS25_026', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS25_027', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS25_028', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS25_029', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS25_030', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS25_031', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS25_032', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS25_033', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS25_034', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS25_035', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS25_036', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS25_037', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS25_038', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS25_039', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS25_040', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS25_041', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS25_042', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS25_043', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS25_044', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS25_045', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS25_046', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS25_047', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS25_048', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS25_049', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS25_050', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS25_051', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS25_052', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS25_053', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS25_054', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS25_055', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS25_056', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS25_057', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS25_058', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS25_059', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS25_060', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS25_061', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS25_062', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS25_063', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS25_064', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS25_065', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS25_066', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS25_067', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS25_068', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS25_069', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS25_070', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS25_071', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS25_072', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS25_073', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS25_074', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS25_075', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS25_076', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS25_077', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS25_078', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS25_079', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS25_080', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS25_081', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS25_082', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS25_083', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS25_084', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS25_085', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS25_086', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS25_087', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS25_088', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS25_089', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS25_090', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS25_091', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS25_092', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS25_093', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS25_094', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS25_095', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS25_096', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS25_097', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS25_098', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS25_099', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS25_100', 24);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS25_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 3, 80, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 4, 70, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 5, 60, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS25_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 3, 80, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 4, 70, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 5, 60, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS25_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 3, 80, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 4, 70, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 5, 60, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS25_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 3, 80, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 4, 70, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 5, 60, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS25_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 3, 80, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 4, 70, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 5, 60, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS25_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 3, 80, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 4, 70, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 5, 60, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS25_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 3, 80, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 4, 70, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 5, 60, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS25_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 3, 80, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 4, 70, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 5, 60, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS25_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 3, 80, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 4, 70, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 5, 60, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS25_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 3, 80, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 4, 70, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 5, 60, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS25_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 4, 70, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 5, 60, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS25_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 3, 80, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 4, 70, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 5, 60, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS25_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 3, 80, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 4, 70, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 5, 60, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS25_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 3, 80, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 5, 60, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS25_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 3, 80, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 4, 70, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 5, 60, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS25_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 3, 80, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 5, 60, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS25_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 3, 80, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 4, 70, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS25_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 3, 80, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 4, 70, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 5, 60, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS25_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 3, 80, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 4, 70, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 5, 60, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS25_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 3, 80, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 4, 70, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 5, 60, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS25_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 3, 80, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 4, 70, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 5, 60, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS25_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 3, 80, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 4, 70, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS25_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 3, 80, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 5, 60, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS25_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 3, 80, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 4, 70, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 5, 60, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS25_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 3, 80, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 4, 70, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 5, 60, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS25_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 3, 80, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 4, 70, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 5, 60, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS25_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 3, 80, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 4, 70, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 5, 60, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS25_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 3, 80, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 4, 70, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 5, 60, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS25_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 3, 80, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 4, 70, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 5, 60, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS25_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 3, 80, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 5, 60, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS25_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 3, 80, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 4, 70, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS25_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 3, 80, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 4, 70, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 5, 60, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS25_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 4, 70, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 5, 60, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS25_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 3, 80, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 4, 70, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 5, 60, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS25_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 3, 80, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 4, 70, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 5, 60, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS25_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 3, 80, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 4, 70, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 5, 60, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS25_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 3, 80, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 5, 60, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS25_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 3, 80, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 4, 70, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 5, 60, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS25_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 5, 60, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS25_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 3, 80, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 4, 70, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 5, 60, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS25_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 3, 80, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 4, 70, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 5, 60, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS25_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 3, 80, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 5, 60, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS25_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 3, 80, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 4, 70, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 5, 60, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS25_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 3, 80, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 4, 70, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 5, 60, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS25_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 3, 80, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 5, 60, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS25_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 3, 80, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 5, 60, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS25_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 4, 70, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 5, 60, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS25_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 4, 70, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 5, 60, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS25_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 3, 80, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 4, 70, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 5, 60, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS25_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 3, 80, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 4, 70, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 5, 60, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS25_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 3, 80, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 4, 70, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 5, 60, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS25_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 3, 80, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 4, 70, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 5, 60, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS25_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 3, 80, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 4, 70, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 5, 60, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS25_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 3, 80, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 5, 60, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS25_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 3, 80, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 5, 60, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS25_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 3, 80, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 4, 70, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 5, 60, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS25_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 3, 80, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 4, 70, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 5, 60, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS25_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 3, 80, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 4, 70, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS25_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 3, 80, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 4, 70, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 5, 60, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS25_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 3, 80, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 4, 70, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 5, 60, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS25_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 3, 80, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 4, 70, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 5, 60, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS25_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 3, 80, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 4, 70, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 5, 60, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS25_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 3, 80, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 4, 70, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 5, 60, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS25_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 3, 80, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 4, 70, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 5, 60, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS25_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 3, 80, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 4, 70, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 5, 60, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS25_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 3, 80, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 5, 60, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS25_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 3, 80, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 4, 70, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 5, 60, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS25_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 3, 80, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 4, 70, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 5, 60, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS25_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 3, 80, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 4, 70, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 5, 60, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS25_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 3, 80, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 4, 70, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 5, 60, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS25_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 3, 80, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 4, 70, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 5, 60, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS25_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 3, 80, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 4, 70, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 5, 60, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS25_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 3, 80, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 5, 60, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS25_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 3, 80, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 4, 70, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 5, 60, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS25_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 3, 80, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 4, 70, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 5, 60, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS25_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 3, 80, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 4, 70, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 5, 60, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS25_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 3, 80, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 4, 70, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 5, 60, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS25_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 3, 80, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 4, 70, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 5, 60, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS25_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 3, 80, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 5, 60, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS25_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 3, 80, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 4, 70, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 5, 60, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS25_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 3, 80, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 4, 70, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 5, 60, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS25_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 3, 80, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 4, 70, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 5, 60, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS25_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 3, 80, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 4, 70, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 5, 60, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS25_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 3, 80, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 4, 70, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS25_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 3, 80, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 4, 70, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 5, 60, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS25_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 3, 80, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 5, 60, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS25_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 3, 80, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 4, 70, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 5, 60, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS25_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 3, 80, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 4, 70, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 5, 60, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS25_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 3, 80, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 4, 70, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 5, 60, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS25_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 3, 80, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 4, 70, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 5, 60, 'CLS045');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS25_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 3, 80, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 4, 70, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 5, 60, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS25_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 3, 80, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 4, 70, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 5, 60, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS25_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 3, 80, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 4, 70, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 5, 60, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS25_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 3, 80, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 4, 70, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 5, 60, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS25_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 3, 80, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 4, 70, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 5, 60, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS25_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 3, 80, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 4, 70, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 5, 60, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS25_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 3, 80, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 4, 70, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 5, 60, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS25_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 3, 80, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 4, 70, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 5, 60, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS25_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 3, 80, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 4, 70, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 5, 60, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS25_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 3, 80, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 4, 70, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 5, 60, 'CLS025');


