-- ==============================================
-- SKENARIO 10: N=100, V=100, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_001', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_002', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_003', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_004', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_006', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_007', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_008', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_009', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_010', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_012', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_013', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_014', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_015', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_017', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_018', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_019', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_021', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_022', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_023', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_024', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_025', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_026', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_027', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_028', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_030', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_031', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_032', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_034', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_035', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_036', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_040', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_041', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_042', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_044', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_046', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_047', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_048', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_049', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_050', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_051', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_052', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_053', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_054', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_056', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_057', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_058', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_059', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_060', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_061', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_062', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_063', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_064', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_065', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_066', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_067', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_068', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_070', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_072', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_073', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_074', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_075', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_076', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_077', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_079', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_080', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_085', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_086', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_087', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_089', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_090', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_091', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_092', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_093', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_094', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_095', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_096', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_097', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_099', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS10_100', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (51, 'MK051', 'Matkul 51', 'A', 'CLS051');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (52, 'MK052', 'Matkul 52', 'A', 'CLS052');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (53, 'MK053', 'Matkul 53', 'A', 'CLS053');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (54, 'MK054', 'Matkul 54', 'A', 'CLS054');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (55, 'MK055', 'Matkul 55', 'A', 'CLS055');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (56, 'MK056', 'Matkul 56', 'A', 'CLS056');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (57, 'MK057', 'Matkul 57', 'A', 'CLS057');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (58, 'MK058', 'Matkul 58', 'A', 'CLS058');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (59, 'MK059', 'Matkul 59', 'A', 'CLS059');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (60, 'MK060', 'Matkul 60', 'A', 'CLS060');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (61, 'MK061', 'Matkul 61', 'A', 'CLS061');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (62, 'MK062', 'Matkul 62', 'A', 'CLS062');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (63, 'MK063', 'Matkul 63', 'A', 'CLS063');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (64, 'MK064', 'Matkul 64', 'A', 'CLS064');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (65, 'MK065', 'Matkul 65', 'A', 'CLS065');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (66, 'MK066', 'Matkul 66', 'A', 'CLS066');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (67, 'MK067', 'Matkul 67', 'A', 'CLS067');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (68, 'MK068', 'Matkul 68', 'A', 'CLS068');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (69, 'MK069', 'Matkul 69', 'A', 'CLS069');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (70, 'MK070', 'Matkul 70', 'A', 'CLS070');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (71, 'MK071', 'Matkul 71', 'A', 'CLS071');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (72, 'MK072', 'Matkul 72', 'A', 'CLS072');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (73, 'MK073', 'Matkul 73', 'A', 'CLS073');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (74, 'MK074', 'Matkul 74', 'A', 'CLS074');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (75, 'MK075', 'Matkul 75', 'A', 'CLS075');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (76, 'MK076', 'Matkul 76', 'A', 'CLS076');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (77, 'MK077', 'Matkul 77', 'A', 'CLS077');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (78, 'MK078', 'Matkul 78', 'A', 'CLS078');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (79, 'MK079', 'Matkul 79', 'A', 'CLS079');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (80, 'MK080', 'Matkul 80', 'A', 'CLS080');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (81, 'MK081', 'Matkul 81', 'A', 'CLS081');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (82, 'MK082', 'Matkul 82', 'A', 'CLS082');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (83, 'MK083', 'Matkul 83', 'A', 'CLS083');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (84, 'MK084', 'Matkul 84', 'A', 'CLS084');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (85, 'MK085', 'Matkul 85', 'A', 'CLS085');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (86, 'MK086', 'Matkul 86', 'A', 'CLS086');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (87, 'MK087', 'Matkul 87', 'A', 'CLS087');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (88, 'MK088', 'Matkul 88', 'A', 'CLS088');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (89, 'MK089', 'Matkul 89', 'A', 'CLS089');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (90, 'MK090', 'Matkul 90', 'A', 'CLS090');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (91, 'MK091', 'Matkul 91', 'A', 'CLS091');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (92, 'MK092', 'Matkul 92', 'A', 'CLS092');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (93, 'MK093', 'Matkul 93', 'A', 'CLS093');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (94, 'MK094', 'Matkul 94', 'A', 'CLS094');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (95, 'MK095', 'Matkul 95', 'A', 'CLS095');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (96, 'MK096', 'Matkul 96', 'A', 'CLS096');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (97, 'MK097', 'Matkul 97', 'A', 'CLS097');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (98, 'MK098', 'Matkul 98', 'A', 'CLS098');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (99, 'MK099', 'Matkul 99', 'A', 'CLS099');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (100, 'MK100', 'Matkul 100', 'A', 'CLS100');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS10_001', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS10_002', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS10_003', 58);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS10_004', 80);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS10_005', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS10_006', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS10_007', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS10_008', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS10_009', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS10_010', 68);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS10_011', 85);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS10_012', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS10_013', 88);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS10_014', 89);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS10_015', 92);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS10_016', 76);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS10_017', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS10_018', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS10_019', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS10_020', 48);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS10_021', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS10_022', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS10_023', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS10_024', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS10_025', 51);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS10_026', 98);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS10_027', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS10_028', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS10_029', 72);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS10_030', 90);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS10_031', 99);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS10_032', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS10_033', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS10_034', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS10_035', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS10_036', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS10_037', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS10_038', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS10_039', 52);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS10_040', 63);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS10_041', 88);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS10_042', 55);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS10_043', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS10_044', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS10_045', 86);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS10_046', 92);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS10_047', 65);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS10_048', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS10_049', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS10_050', 54);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS10_051', 81);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS10_052', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS10_053', 97);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS10_054', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS10_055', 56);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS10_056', 98);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS10_057', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS10_058', 53);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS10_059', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS10_060', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS10_061', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS10_062', 62);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS10_063', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS10_064', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS10_065', 98);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS10_066', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS10_067', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS10_068', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS10_069', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS10_070', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS10_071', 78);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS10_072', 87);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS10_073', 75);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS10_074', 55);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS10_075', 71);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS10_076', 60);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS10_077', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS10_078', 69);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS10_079', 83);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS10_080', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS10_081', 74);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS10_082', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS10_083', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS10_084', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS10_085', 60);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS10_086', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS10_087', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS10_088', 52);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS10_089', 72);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS10_090', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS10_091', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS10_092', 69);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS10_093', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS10_094', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS10_095', 90);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS10_096', 69);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS10_097', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS10_098', 65);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS10_099', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS10_100', 9);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS10_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS10_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS10_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS080');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS10_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS067');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS10_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS10_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS061');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS10_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS083');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS10_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS065');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS10_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS095');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS10_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS091');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS10_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS051');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS10_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS10_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS10_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS081');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS079');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS10_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS051');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS10_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS064');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS094');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS10_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS084');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS10_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS053');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS10_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS076');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS10_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS053');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS092');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS10_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS081');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS10_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS074');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS059');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS10_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS078');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS10_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS090');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS10_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS082');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS090');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS10_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS080');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS10_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS093');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS10_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS10_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS060');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS10_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS065');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS10_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS10_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS052');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS098');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS10_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS067');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS10_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS056');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS076');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS10_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS061');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS10_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS086');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS10_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS10_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS077');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS10_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS095');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS10_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS082');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS10_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS086');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS10_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS059');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS078');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS10_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS086');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS10_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS060');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS10_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS10_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS081');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS10_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS062');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS10_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS066');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS10_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS10_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS068');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS060');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS10_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS100');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS052');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS10_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS075');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS10_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS077');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS10_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS084');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS094');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS10_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS10_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS066');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS10_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS078');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS10_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS093');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS10_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS10_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS077');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS10_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS10_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS080');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS061');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS10_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS069');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS10_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS071');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS062');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS10_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS10_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS057');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS10_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS10_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS095');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS10_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS10_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS10_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS085');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS10_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS079');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS084');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS10_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS069');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS10_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS10_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS080');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS10_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS10_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS10_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS10_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS064');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS10_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS097');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS10_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS075');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS10_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS088');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS10_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS090');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS059');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS10_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS10_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS088');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS093');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS10_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS071');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS10_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS064');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS10_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS074');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS10_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS093');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS077');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS10_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS060');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS10_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS10_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS082');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS096');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS10_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS078');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS10_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS051');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS095');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS10_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS10_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS10_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS076');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS10_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS056');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS075');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS10_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS089');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS10_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS091');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS033');


