-- ==============================================
-- SKENARIO 23: N=100, V=50, P=3
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_001', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_002', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_003', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_005', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_006', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_007', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_008', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_009', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_012', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_013', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_014', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_015', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_016', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_017', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_018', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_021', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_022', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_023', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_024', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_025', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_026', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_027', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_028', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_029', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_030', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_032', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_034', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_035', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_036', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_040', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_041', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_042', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_044', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_045', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_046', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_047', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_048', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_050', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_051', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_052', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_053', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_054', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_056', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_057', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_058', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_059', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_060', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_061', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_062', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_063', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_064', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_065', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_066', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_067', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_070', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_072', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_073', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_074', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_075', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_076', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_077', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_078', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_079', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_080', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_085', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_086', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_087', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_089', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_090', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_091', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_092', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_094', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_095', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_096', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_097', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_099', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS23_100', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS23_001', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS23_002', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS23_003', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS23_004', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS23_005', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS23_006', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS23_007', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS23_008', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS23_009', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS23_010', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS23_011', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS23_012', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS23_013', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS23_014', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS23_015', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS23_016', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS23_017', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS23_018', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS23_019', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS23_020', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS23_021', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS23_022', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS23_023', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS23_024', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS23_025', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS23_026', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS23_027', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS23_028', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS23_029', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS23_030', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS23_031', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS23_032', 42);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS23_033', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS23_034', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS23_035', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS23_036', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS23_037', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS23_038', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS23_039', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS23_040', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS23_041', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS23_042', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS23_043', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS23_044', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS23_045', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS23_046', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS23_047', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS23_048', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS23_049', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS23_050', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS23_051', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS23_052', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS23_053', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS23_054', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS23_055', 41);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS23_056', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS23_057', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS23_058', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS23_059', 45);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS23_060', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS23_061', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS23_062', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS23_063', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS23_064', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS23_065', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS23_066', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS23_067', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS23_068', 41);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS23_069', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS23_070', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS23_071', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS23_072', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS23_073', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS23_074', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS23_075', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS23_076', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS23_077', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS23_078', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS23_079', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS23_080', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS23_081', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS23_082', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS23_083', 47);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS23_084', 44);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS23_085', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS23_086', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS23_087', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS23_088', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS23_089', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS23_090', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS23_091', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS23_092', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS23_093', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS23_094', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS23_095', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS23_096', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS23_097', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS23_098', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS23_099', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS23_100', 2);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS23_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 3, 80, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS23_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 3, 80, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS23_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 3, 80, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS23_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 3, 80, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS23_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 3, 80, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS23_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 3, 80, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS23_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 3, 80, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS23_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 3, 80, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS23_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 3, 80, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS23_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 3, 80, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS23_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 3, 80, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS23_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 3, 80, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS23_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 3, 80, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS23_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 3, 80, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS23_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 3, 80, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS23_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 3, 80, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS23_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 3, 80, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS23_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 3, 80, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS23_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 3, 80, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS23_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 3, 80, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS23_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 3, 80, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS23_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 3, 80, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS23_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 3, 80, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS23_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 3, 80, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS23_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 3, 80, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS23_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 3, 80, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS23_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 3, 80, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS23_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 3, 80, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS23_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 3, 80, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS23_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 3, 80, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS23_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 3, 80, 'CLS045');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS23_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 3, 80, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS23_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 3, 80, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS23_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 3, 80, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS23_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 3, 80, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS23_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 3, 80, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS23_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 3, 80, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS23_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 3, 80, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS23_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 3, 80, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS23_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 3, 80, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS23_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 3, 80, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS23_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 3, 80, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS23_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 3, 80, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS23_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 3, 80, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS23_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 3, 80, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS23_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 3, 80, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS23_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 3, 80, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS23_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 3, 80, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS23_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 3, 80, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS23_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 3, 80, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS23_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 3, 80, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS23_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 3, 80, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS23_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 3, 80, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS23_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 3, 80, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS23_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 3, 80, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS23_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 3, 80, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS23_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 3, 80, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS23_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 3, 80, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS23_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 3, 80, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS23_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 3, 80, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS23_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 3, 80, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS23_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 3, 80, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS23_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 3, 80, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS23_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 3, 80, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS23_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 3, 80, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS23_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 3, 80, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS23_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 3, 80, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS23_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 3, 80, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS23_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 3, 80, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS23_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 3, 80, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS23_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 3, 80, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS23_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 3, 80, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS23_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 3, 80, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS23_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 3, 80, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS23_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 3, 80, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS23_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 3, 80, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS23_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 3, 80, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS23_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 3, 80, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS23_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 3, 80, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS23_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 3, 80, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS23_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 3, 80, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS23_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 3, 80, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS23_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 3, 80, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS23_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 3, 80, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS23_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 3, 80, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS23_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 3, 80, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS23_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 3, 80, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS23_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 3, 80, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS23_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 3, 80, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS23_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 3, 80, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS23_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 3, 80, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS23_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS047');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 3, 80, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS23_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 3, 80, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS23_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 3, 80, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS23_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 3, 80, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS23_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 3, 80, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS23_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 3, 80, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS23_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 3, 80, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS23_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 3, 80, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS23_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 3, 80, 'CLS003');


