-- ==============================================
-- SKENARIO 5: N=100, V=40, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_001', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_002', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_003', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_004', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_006', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_007', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_008', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_009', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_011', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_012', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_013', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_014', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_015', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_016', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_017', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_018', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_019', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_021', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_022', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_024', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_025', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_026', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_027', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_028', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_032', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_034', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_036', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_037', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_038', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_039', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_040', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_041', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_042', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_043', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_044', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_046', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_047', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_048', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_050', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_051', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_052', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_053', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_054', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_056', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_057', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_058', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_059', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_060', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_061', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_062', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_063', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_064', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_065', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_066', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_067', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_068', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_069', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_070', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_071', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_072', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_073', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_074', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_075', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_076', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_077', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_078', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_079', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_080', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_081', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_082', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_085', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_086', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_087', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_089', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_090', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_091', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_092', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_093', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_094', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_095', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_096', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_097', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_098', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_099', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS5_100', 'Informatika', 2022, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS5_001', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS5_002', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS5_003', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS5_004', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS5_005', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS5_006', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS5_007', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS5_008', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS5_009', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS5_010', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS5_011', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS5_012', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS5_013', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS5_014', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS5_015', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS5_016', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS5_017', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS5_018', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS5_019', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS5_020', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS5_021', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS5_022', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS5_023', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS5_024', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS5_025', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS5_026', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS5_027', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS5_028', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS5_029', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS5_030', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS5_031', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS5_032', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS5_033', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS5_034', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS5_035', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS5_036', 31);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS5_037', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS5_038', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS5_039', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS5_040', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS5_041', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS5_042', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS5_043', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS5_044', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS5_045', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS5_046', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS5_047', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS5_048', 17);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS5_049', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS5_050', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS5_051', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS5_052', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS5_053', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS5_054', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS5_055', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS5_056', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS5_057', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS5_058', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS5_059', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS5_060', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS5_061', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS5_062', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS5_063', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS5_064', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS5_065', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS5_066', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS5_067', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS5_068', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS5_069', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS5_070', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS5_071', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS5_072', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS5_073', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS5_074', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS5_075', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS5_076', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS5_077', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS5_078', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS5_079', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS5_080', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS5_081', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS5_082', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS5_083', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS5_084', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS5_085', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS5_086', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS5_087', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS5_088', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS5_089', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS5_090', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS5_091', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS5_092', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS5_093', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS5_094', 32);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS5_095', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS5_096', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS5_097', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS5_098', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS5_099', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS5_100', 28);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS5_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS5_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS5_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS5_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS5_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS5_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS5_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS5_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS5_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS5_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS5_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS5_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS5_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS5_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS5_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS5_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS5_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS5_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS5_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS5_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS5_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS5_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS5_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS5_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS5_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS036');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS5_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS5_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS5_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS5_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS5_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS5_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS5_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS5_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS5_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS5_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS5_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS5_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS5_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS5_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS5_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS5_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS5_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS5_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS5_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS5_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS5_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS5_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS5_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS5_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS5_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS5_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS5_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS5_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS5_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS5_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS5_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS5_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS5_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS5_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS5_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS5_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS5_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS5_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS5_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS5_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS5_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS040');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS5_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS5_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS5_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS5_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS5_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS5_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS5_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS5_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS5_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS5_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS5_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS5_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS5_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS5_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS5_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS5_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS5_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS5_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS5_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS5_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS012');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS5_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS5_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS5_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS5_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS5_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS5_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS020');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS5_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS5_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS5_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS5_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS5_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS5_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS5_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS022');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS5_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS040');


