-- ==============================================
-- SKENARIO 9: N=100, V=80, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_001', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_002', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_003', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_004', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_006', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_007', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_008', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_009', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_010', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_012', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_013', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_014', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_015', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_016', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_017', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_018', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_019', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_021', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_022', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_024', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_025', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_027', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_028', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_031', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_032', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_033', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_034', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_035', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_036', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_037', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_039', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_040', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_041', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_042', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_043', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_044', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_046', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_047', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_048', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_049', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_050', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_051', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_052', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_053', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_054', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_055', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_056', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_057', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_058', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_059', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_060', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_061', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_062', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_063', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_064', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_065', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_066', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_067', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_070', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_072', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_073', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_074', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_075', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_076', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_077', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_079', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_080', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_083', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_084', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_085', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_086', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_087', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_088', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_089', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_090', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_091', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_092', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_093', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_094', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_095', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_096', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_097', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_098', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_099', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS9_100', 'Informatika', 2023, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (51, 'MK051', 'Matkul 51', 'A', 'CLS051');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (52, 'MK052', 'Matkul 52', 'A', 'CLS052');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (53, 'MK053', 'Matkul 53', 'A', 'CLS053');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (54, 'MK054', 'Matkul 54', 'A', 'CLS054');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (55, 'MK055', 'Matkul 55', 'A', 'CLS055');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (56, 'MK056', 'Matkul 56', 'A', 'CLS056');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (57, 'MK057', 'Matkul 57', 'A', 'CLS057');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (58, 'MK058', 'Matkul 58', 'A', 'CLS058');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (59, 'MK059', 'Matkul 59', 'A', 'CLS059');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (60, 'MK060', 'Matkul 60', 'A', 'CLS060');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (61, 'MK061', 'Matkul 61', 'A', 'CLS061');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (62, 'MK062', 'Matkul 62', 'A', 'CLS062');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (63, 'MK063', 'Matkul 63', 'A', 'CLS063');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (64, 'MK064', 'Matkul 64', 'A', 'CLS064');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (65, 'MK065', 'Matkul 65', 'A', 'CLS065');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (66, 'MK066', 'Matkul 66', 'A', 'CLS066');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (67, 'MK067', 'Matkul 67', 'A', 'CLS067');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (68, 'MK068', 'Matkul 68', 'A', 'CLS068');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (69, 'MK069', 'Matkul 69', 'A', 'CLS069');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (70, 'MK070', 'Matkul 70', 'A', 'CLS070');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (71, 'MK071', 'Matkul 71', 'A', 'CLS071');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (72, 'MK072', 'Matkul 72', 'A', 'CLS072');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (73, 'MK073', 'Matkul 73', 'A', 'CLS073');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (74, 'MK074', 'Matkul 74', 'A', 'CLS074');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (75, 'MK075', 'Matkul 75', 'A', 'CLS075');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (76, 'MK076', 'Matkul 76', 'A', 'CLS076');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (77, 'MK077', 'Matkul 77', 'A', 'CLS077');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (78, 'MK078', 'Matkul 78', 'A', 'CLS078');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (79, 'MK079', 'Matkul 79', 'A', 'CLS079');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (80, 'MK080', 'Matkul 80', 'A', 'CLS080');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS9_001', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS9_002', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS9_003', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS9_004', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS9_005', 51);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS9_006', 63);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS9_007', 30);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS9_008', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS9_009', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS9_010', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS9_011', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS9_012', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS9_013', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS9_014', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS9_015', 59);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS9_016', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS9_017', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS9_018', 62);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS9_019', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS9_020', 59);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS9_021', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS9_022', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS9_023', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS9_024', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS9_025', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS9_026', 80);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS9_027', 43);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS9_028', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS9_029', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS9_030', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS9_031', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS9_032', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS9_033', 51);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS9_034', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS9_035', 67);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS9_036', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS9_037', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS9_038', 59);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS9_039', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS9_040', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS9_041', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS9_042', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS9_043', 75);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS9_044', 71);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS9_045', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS9_046', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS9_047', 16);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS9_048', 78);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS9_049', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS9_050', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS9_051', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS9_052', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS9_053', 25);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS9_054', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS9_055', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS9_056', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS9_057', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS9_058', 62);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS9_059', 15);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS9_060', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS9_061', 73);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS9_062', 79);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS9_063', 69);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS9_064', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS9_065', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS9_066', 57);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS9_067', 78);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS9_068', 52);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS9_069', 56);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS9_070', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS9_071', 67);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS9_072', 64);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS9_073', 64);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS9_074', 41);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS9_075', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS9_076', 58);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS9_077', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS9_078', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS9_079', 35);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS9_080', 70);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS9_081', 54);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS9_082', 65);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS9_083', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS9_084', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS9_085', 58);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS9_086', 51);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS9_087', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS9_088', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS9_089', 58);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS9_090', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS9_091', 78);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS9_092', 28);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS9_093', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS9_094', 76);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS9_095', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS9_096', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS9_097', 68);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS9_098', 74);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS9_099', 77);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS9_100', 58);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS9_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS9_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS075');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS9_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS045');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS9_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS9_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS028');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS9_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS075');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS9_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS079');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS9_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS9_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS062');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS066');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS9_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS071');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS9_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS072');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS9_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS036');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS077');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS9_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS016');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS058');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS9_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS9_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS069');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS9_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS075');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS9_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS052');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS9_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS063');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS9_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS055');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS056');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS9_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS9_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS9_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS072');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS9_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS9_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS066');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS9_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS052');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS072');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS9_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS054');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS9_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS054');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS070');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS9_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS072');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS9_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS9_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS9_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS051');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS013');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS9_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS9_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS9_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS9_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS073');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS9_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS054');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS9_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS078');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS9_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS9_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS080');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS9_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS066');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS9_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS068');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS054');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS9_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS055');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS9_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS071');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS9_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS059');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS9_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS055');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS9_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS9_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS9_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS073');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS049');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS9_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS9_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS9_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS056');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS9_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS045');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS078');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS9_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS9_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS035');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS9_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS077');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS9_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS9_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS067');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS9_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS067');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS074');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS9_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS9_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS075');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS068');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS9_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS022');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS9_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS9_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS056');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS9_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS9_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS062');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS041');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS9_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS078');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS9_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS062');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS064');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS9_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS024');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS9_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS055');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS9_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS059');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS9_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS9_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS9_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS9_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS9_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS037');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS9_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS9_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS9_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS9_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS067');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS9_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS9_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS076');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS067');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS9_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS038');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS9_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS015');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS9_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS056');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS9_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS017');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS9_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS9_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS080');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS021');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS9_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS9_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS076');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS9_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS073');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS9_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS9_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS9_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS031');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS9_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS9_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS011');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS9_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS9_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS016');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS9_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS080');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS9_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS060');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS9_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS072');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS030');


