-- ==============================================
-- SKENARIO 2: N=100, V=10, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_001', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_002', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_003', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_004', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_005', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_006', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_007', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_008', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_009', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_010', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_011', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_012', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_013', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_015', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_017', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_018', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_019', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_020', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_021', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_022', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_024', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_025', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_026', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_027', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_028', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_029', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_030', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_032', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_033', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_034', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_036', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_039', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_040', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_041', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_042', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_043', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_044', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_045', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_046', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_047', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_048', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_049', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_050', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_051', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_052', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_053', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_054', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_056', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_057', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_058', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_059', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_060', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_061', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_062', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_063', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_064', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_065', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_066', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_067', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_068', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_069', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_070', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_071', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_072', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_073', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_074', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_075', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_076', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_077', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_078', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_079', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_080', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_081', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_082', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_083', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_084', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_085', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_086', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_087', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_088', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_089', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_090', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_091', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_092', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_093', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_094', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_095', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_096', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_097', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_098', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_099', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS2_100', 'Informatika', 2022, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS2_001', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS2_002', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS2_003', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS2_004', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS2_005', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS2_006', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS2_007', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS2_008', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS2_009', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS2_010', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS2_011', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS2_012', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS2_013', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS2_014', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS2_015', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS2_016', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS2_017', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS2_018', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS2_019', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS2_020', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS2_021', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS2_022', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS2_023', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS2_024', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS2_025', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS2_026', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS2_027', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS2_028', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS2_029', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS2_030', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS2_031', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS2_032', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS2_033', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS2_034', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS2_035', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS2_036', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS2_037', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS2_038', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS2_039', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS2_040', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS2_041', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS2_042', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS2_043', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS2_044', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS2_045', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS2_046', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS2_047', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS2_048', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS2_049', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS2_050', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS2_051', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS2_052', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS2_053', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS2_054', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS2_055', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS2_056', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS2_057', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS2_058', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS2_059', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS2_060', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (61, 'MHS2_061', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (62, 'MHS2_062', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (63, 'MHS2_063', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (64, 'MHS2_064', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (65, 'MHS2_065', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (66, 'MHS2_066', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (67, 'MHS2_067', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (68, 'MHS2_068', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (69, 'MHS2_069', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (70, 'MHS2_070', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (71, 'MHS2_071', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (72, 'MHS2_072', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (73, 'MHS2_073', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (74, 'MHS2_074', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (75, 'MHS2_075', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (76, 'MHS2_076', 8);
INSERT INTO enrollments (id, nim, class_id) VALUES (77, 'MHS2_077', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (78, 'MHS2_078', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (79, 'MHS2_079', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (80, 'MHS2_080', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (81, 'MHS2_081', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (82, 'MHS2_082', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (83, 'MHS2_083', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (84, 'MHS2_084', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (85, 'MHS2_085', 4);
INSERT INTO enrollments (id, nim, class_id) VALUES (86, 'MHS2_086', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (87, 'MHS2_087', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (88, 'MHS2_088', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (89, 'MHS2_089', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (90, 'MHS2_090', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (91, 'MHS2_091', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (92, 'MHS2_092', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (93, 'MHS2_093', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (94, 'MHS2_094', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (95, 'MHS2_095', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (96, 'MHS2_096', 2);
INSERT INTO enrollments (id, nim, class_id) VALUES (97, 'MHS2_097', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (98, 'MHS2_098', 5);
INSERT INTO enrollments (id, nim, class_id) VALUES (99, 'MHS2_099', 1);
INSERT INTO enrollments (id, nim, class_id) VALUES (100, 'MHS2_100', 3);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS2_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS2_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS2_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS2_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS2_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS2_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS2_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS2_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS2_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS2_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS2_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS2_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS2_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS2_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS2_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS2_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS2_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS2_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS2_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS2_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS2_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS2_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS2_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS2_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS2_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS2_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS2_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS2_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS2_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS2_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS2_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS2_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS2_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS2_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS2_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS2_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS2_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS2_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS2_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS2_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS2_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS2_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS2_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS2_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS2_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS2_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS2_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS2_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS2_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS2_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS2_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS2_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS2_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS2_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS2_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS2_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS2_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS2_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS2_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS2_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (61, 'MHS2_061', 61);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (61, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (62, 'MHS2_062', 62);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (62, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (63, 'MHS2_063', 63);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (63, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (64, 'MHS2_064', 64);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (64, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (65, 'MHS2_065', 65);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (65, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (66, 'MHS2_066', 66);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (66, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (67, 'MHS2_067', 67);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (67, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (68, 'MHS2_068', 68);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (68, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (69, 'MHS2_069', 69);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (69, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (70, 'MHS2_070', 70);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (70, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (71, 'MHS2_071', 71);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (71, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (72, 'MHS2_072', 72);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (72, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (73, 'MHS2_073', 73);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (73, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (74, 'MHS2_074', 74);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (74, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (75, 'MHS2_075', 75);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (75, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (76, 'MHS2_076', 76);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (76, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (77, 'MHS2_077', 77);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (77, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (78, 'MHS2_078', 78);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (78, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (79, 'MHS2_079', 79);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (79, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (80, 'MHS2_080', 80);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (80, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (81, 'MHS2_081', 81);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (81, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (82, 'MHS2_082', 82);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (82, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (83, 'MHS2_083', 83);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (83, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (84, 'MHS2_084', 84);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 1, 100, 'CLS007');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (84, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (85, 'MHS2_085', 85);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 1, 100, 'CLS002');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (85, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (86, 'MHS2_086', 86);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (86, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (87, 'MHS2_087', 87);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (87, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (88, 'MHS2_088', 88);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (88, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (89, 'MHS2_089', 89);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (89, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (90, 'MHS2_090', 90);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 1, 100, 'CLS009');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (90, 2, 90, 'CLS004');
INSERT INTO preferences (id, nim, swap_course) VALUES (91, 'MHS2_091', 91);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (91, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (92, 'MHS2_092', 92);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (92, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (93, 'MHS2_093', 93);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (93, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (94, 'MHS2_094', 94);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (94, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (95, 'MHS2_095', 95);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (95, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (96, 'MHS2_096', 96);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 1, 100, 'CLS008');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (96, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (97, 'MHS2_097', 97);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (97, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (98, 'MHS2_098', 98);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 1, 100, 'CLS006');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (98, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (99, 'MHS2_099', 99);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (99, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (100, 'MHS2_100', 100);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (100, 2, 90, 'CLS007');


