-- ==============================================
-- SKENARIO 16: N=60, V=50, P=2
-- ==============================================

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE preferences;
TRUNCATE TABLE pref_courses;
TRUNCATE TABLE swap_results;
TRUNCATE TABLE students;
TRUNCATE TABLE course_classes;
TRUNCATE TABLE enrollments;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_001', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_002', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_003', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_004', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_005', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_006', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_007', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_008', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_009', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_010', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_011', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_012', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_013', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_014', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_015', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_016', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_017', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_018', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_019', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_020', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_021', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_022', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_023', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_024', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_025', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_026', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_027', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_028', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_029', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_030', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_031', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_032', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_033', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_034', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_035', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_036', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_037', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_038', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_039', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_040', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_041', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_042', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_043', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_044', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_045', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_046', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_047', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_048', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_049', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_050', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_051', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_052', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_053', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_054', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_055', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_056', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_057', 'Informatika', 2023, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_058', 'Informatika', 2024, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_059', 'Informatika', 2022, '1234');
INSERT INTO students (nim, major, angkatan, password) VALUES ('MHS16_060', 'Informatika', 2024, '1234');

INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (1, 'MK001', 'Matkul 1', 'A', 'CLS001');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (2, 'MK002', 'Matkul 2', 'A', 'CLS002');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (3, 'MK003', 'Matkul 3', 'A', 'CLS003');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (4, 'MK004', 'Matkul 4', 'A', 'CLS004');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (5, 'MK005', 'Matkul 5', 'A', 'CLS005');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (6, 'MK006', 'Matkul 6', 'A', 'CLS006');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (7, 'MK007', 'Matkul 7', 'A', 'CLS007');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (8, 'MK008', 'Matkul 8', 'A', 'CLS008');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (9, 'MK009', 'Matkul 9', 'A', 'CLS009');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (10, 'MK010', 'Matkul 10', 'A', 'CLS010');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (11, 'MK011', 'Matkul 11', 'A', 'CLS011');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (12, 'MK012', 'Matkul 12', 'A', 'CLS012');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (13, 'MK013', 'Matkul 13', 'A', 'CLS013');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (14, 'MK014', 'Matkul 14', 'A', 'CLS014');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (15, 'MK015', 'Matkul 15', 'A', 'CLS015');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (16, 'MK016', 'Matkul 16', 'A', 'CLS016');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (17, 'MK017', 'Matkul 17', 'A', 'CLS017');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (18, 'MK018', 'Matkul 18', 'A', 'CLS018');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (19, 'MK019', 'Matkul 19', 'A', 'CLS019');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (20, 'MK020', 'Matkul 20', 'A', 'CLS020');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (21, 'MK021', 'Matkul 21', 'A', 'CLS021');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (22, 'MK022', 'Matkul 22', 'A', 'CLS022');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (23, 'MK023', 'Matkul 23', 'A', 'CLS023');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (24, 'MK024', 'Matkul 24', 'A', 'CLS024');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (25, 'MK025', 'Matkul 25', 'A', 'CLS025');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (26, 'MK026', 'Matkul 26', 'A', 'CLS026');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (27, 'MK027', 'Matkul 27', 'A', 'CLS027');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (28, 'MK028', 'Matkul 28', 'A', 'CLS028');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (29, 'MK029', 'Matkul 29', 'A', 'CLS029');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (30, 'MK030', 'Matkul 30', 'A', 'CLS030');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (31, 'MK031', 'Matkul 31', 'A', 'CLS031');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (32, 'MK032', 'Matkul 32', 'A', 'CLS032');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (33, 'MK033', 'Matkul 33', 'A', 'CLS033');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (34, 'MK034', 'Matkul 34', 'A', 'CLS034');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (35, 'MK035', 'Matkul 35', 'A', 'CLS035');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (36, 'MK036', 'Matkul 36', 'A', 'CLS036');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (37, 'MK037', 'Matkul 37', 'A', 'CLS037');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (38, 'MK038', 'Matkul 38', 'A', 'CLS038');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (39, 'MK039', 'Matkul 39', 'A', 'CLS039');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (40, 'MK040', 'Matkul 40', 'A', 'CLS040');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (41, 'MK041', 'Matkul 41', 'A', 'CLS041');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (42, 'MK042', 'Matkul 42', 'A', 'CLS042');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (43, 'MK043', 'Matkul 43', 'A', 'CLS043');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (44, 'MK044', 'Matkul 44', 'A', 'CLS044');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (45, 'MK045', 'Matkul 45', 'A', 'CLS045');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (46, 'MK046', 'Matkul 46', 'A', 'CLS046');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (47, 'MK047', 'Matkul 47', 'A', 'CLS047');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (48, 'MK048', 'Matkul 48', 'A', 'CLS048');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (49, 'MK049', 'Matkul 49', 'A', 'CLS049');
INSERT INTO course_classes (id, course_code, course_name, class_name, group_code) VALUES (50, 'MK050', 'Matkul 50', 'A', 'CLS050');

INSERT INTO enrollments (id, nim, class_id) VALUES (1, 'MHS16_001', 14);
INSERT INTO enrollments (id, nim, class_id) VALUES (2, 'MHS16_002', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (3, 'MHS16_003', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (4, 'MHS16_004', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (5, 'MHS16_005', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (6, 'MHS16_006', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (7, 'MHS16_007', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (8, 'MHS16_008', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (9, 'MHS16_009', 40);
INSERT INTO enrollments (id, nim, class_id) VALUES (10, 'MHS16_010', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (11, 'MHS16_011', 42);
INSERT INTO enrollments (id, nim, class_id) VALUES (12, 'MHS16_012', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (13, 'MHS16_013', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (14, 'MHS16_014', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (15, 'MHS16_015', 42);
INSERT INTO enrollments (id, nim, class_id) VALUES (16, 'MHS16_016', 19);
INSERT INTO enrollments (id, nim, class_id) VALUES (17, 'MHS16_017', 3);
INSERT INTO enrollments (id, nim, class_id) VALUES (18, 'MHS16_018', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (19, 'MHS16_019', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (20, 'MHS16_020', 7);
INSERT INTO enrollments (id, nim, class_id) VALUES (21, 'MHS16_021', 24);
INSERT INTO enrollments (id, nim, class_id) VALUES (22, 'MHS16_022', 21);
INSERT INTO enrollments (id, nim, class_id) VALUES (23, 'MHS16_023', 26);
INSERT INTO enrollments (id, nim, class_id) VALUES (24, 'MHS16_024', 42);
INSERT INTO enrollments (id, nim, class_id) VALUES (25, 'MHS16_025', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (26, 'MHS16_026', 11);
INSERT INTO enrollments (id, nim, class_id) VALUES (27, 'MHS16_027', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (28, 'MHS16_028', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (29, 'MHS16_029', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (30, 'MHS16_030', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (31, 'MHS16_031', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (32, 'MHS16_032', 29);
INSERT INTO enrollments (id, nim, class_id) VALUES (33, 'MHS16_033', 10);
INSERT INTO enrollments (id, nim, class_id) VALUES (34, 'MHS16_034', 9);
INSERT INTO enrollments (id, nim, class_id) VALUES (35, 'MHS16_035', 13);
INSERT INTO enrollments (id, nim, class_id) VALUES (36, 'MHS16_036', 42);
INSERT INTO enrollments (id, nim, class_id) VALUES (37, 'MHS16_037', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (38, 'MHS16_038', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (39, 'MHS16_039', 50);
INSERT INTO enrollments (id, nim, class_id) VALUES (40, 'MHS16_040', 46);
INSERT INTO enrollments (id, nim, class_id) VALUES (41, 'MHS16_041', 49);
INSERT INTO enrollments (id, nim, class_id) VALUES (42, 'MHS16_042', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (43, 'MHS16_043', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (44, 'MHS16_044', 6);
INSERT INTO enrollments (id, nim, class_id) VALUES (45, 'MHS16_045', 23);
INSERT INTO enrollments (id, nim, class_id) VALUES (46, 'MHS16_046', 22);
INSERT INTO enrollments (id, nim, class_id) VALUES (47, 'MHS16_047', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (48, 'MHS16_048', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (49, 'MHS16_049', 37);
INSERT INTO enrollments (id, nim, class_id) VALUES (50, 'MHS16_050', 27);
INSERT INTO enrollments (id, nim, class_id) VALUES (51, 'MHS16_051', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (52, 'MHS16_052', 18);
INSERT INTO enrollments (id, nim, class_id) VALUES (53, 'MHS16_053', 20);
INSERT INTO enrollments (id, nim, class_id) VALUES (54, 'MHS16_054', 12);
INSERT INTO enrollments (id, nim, class_id) VALUES (55, 'MHS16_055', 33);
INSERT INTO enrollments (id, nim, class_id) VALUES (56, 'MHS16_056', 34);
INSERT INTO enrollments (id, nim, class_id) VALUES (57, 'MHS16_057', 38);
INSERT INTO enrollments (id, nim, class_id) VALUES (58, 'MHS16_058', 36);
INSERT INTO enrollments (id, nim, class_id) VALUES (59, 'MHS16_059', 39);
INSERT INTO enrollments (id, nim, class_id) VALUES (60, 'MHS16_060', 21);

INSERT INTO preferences (id, nim, swap_course) VALUES (1, 'MHS16_001', 1);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (1, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (2, 'MHS16_002', 2);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (2, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (3, 'MHS16_003', 3);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 1, 100, 'CLS046');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (3, 2, 90, 'CLS037');
INSERT INTO preferences (id, nim, swap_course) VALUES (4, 'MHS16_004', 4);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (4, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (5, 'MHS16_005', 5);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (5, 2, 90, 'CLS006');
INSERT INTO preferences (id, nim, swap_course) VALUES (6, 'MHS16_006', 6);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (6, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (7, 'MHS16_007', 7);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 1, 100, 'CLS012');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (7, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (8, 'MHS16_008', 8);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (8, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (9, 'MHS16_009', 9);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (9, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (10, 'MHS16_010', 10);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 1, 100, 'CLS030');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (10, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (11, 'MHS16_011', 11);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (11, 2, 90, 'CLS014');
INSERT INTO preferences (id, nim, swap_course) VALUES (12, 'MHS16_012', 12);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (12, 2, 90, 'CLS044');
INSERT INTO preferences (id, nim, swap_course) VALUES (13, 'MHS16_013', 13);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (13, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (14, 'MHS16_014', 14);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 1, 100, 'CLS019');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (14, 2, 90, 'CLS015');
INSERT INTO preferences (id, nim, swap_course) VALUES (15, 'MHS16_015', 15);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (15, 2, 90, 'CLS027');
INSERT INTO preferences (id, nim, swap_course) VALUES (16, 'MHS16_016', 16);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 1, 100, 'CLS001');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (16, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (17, 'MHS16_017', 17);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 1, 100, 'CLS018');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (17, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (18, 'MHS16_018', 18);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (18, 2, 90, 'CLS019');
INSERT INTO preferences (id, nim, swap_course) VALUES (19, 'MHS16_019', 19);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 1, 100, 'CLS033');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (19, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (20, 'MHS16_020', 20);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 1, 100, 'CLS020');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (20, 2, 90, 'CLS030');
INSERT INTO preferences (id, nim, swap_course) VALUES (21, 'MHS16_021', 21);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 1, 100, 'CLS041');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (21, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (22, 'MHS16_022', 22);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 1, 100, 'CLS042');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (22, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (23, 'MHS16_023', 23);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (23, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (24, 'MHS16_024', 24);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 1, 100, 'CLS013');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (24, 2, 90, 'CLS008');
INSERT INTO preferences (id, nim, swap_course) VALUES (25, 'MHS16_025', 25);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (25, 2, 90, 'CLS024');
INSERT INTO preferences (id, nim, swap_course) VALUES (26, 'MHS16_026', 26);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (26, 2, 90, 'CLS023');
INSERT INTO preferences (id, nim, swap_course) VALUES (27, 'MHS16_027', 27);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (27, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (28, 'MHS16_028', 28);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 1, 100, 'CLS029');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (28, 2, 90, 'CLS046');
INSERT INTO preferences (id, nim, swap_course) VALUES (29, 'MHS16_029', 29);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 1, 100, 'CLS031');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (29, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (30, 'MHS16_030', 30);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 1, 100, 'CLS004');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (30, 2, 90, 'CLS039');
INSERT INTO preferences (id, nim, swap_course) VALUES (31, 'MHS16_031', 31);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 1, 100, 'CLS048');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (31, 2, 90, 'CLS034');
INSERT INTO preferences (id, nim, swap_course) VALUES (32, 'MHS16_032', 32);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (32, 2, 90, 'CLS009');
INSERT INTO preferences (id, nim, swap_course) VALUES (33, 'MHS16_033', 33);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 1, 100, 'CLS003');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (33, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (34, 'MHS16_034', 34);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (34, 2, 90, 'CLS047');
INSERT INTO preferences (id, nim, swap_course) VALUES (35, 'MHS16_035', 35);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 1, 100, 'CLS049');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (35, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (36, 'MHS16_036', 36);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (36, 2, 90, 'CLS038');
INSERT INTO preferences (id, nim, swap_course) VALUES (37, 'MHS16_037', 37);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 1, 100, 'CLS026');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (37, 2, 90, 'CLS032');
INSERT INTO preferences (id, nim, swap_course) VALUES (38, 'MHS16_038', 38);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 1, 100, 'CLS021');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (38, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (39, 'MHS16_039', 39);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 1, 100, 'CLS028');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (39, 2, 90, 'CLS007');
INSERT INTO preferences (id, nim, swap_course) VALUES (40, 'MHS16_040', 40);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (40, 2, 90, 'CLS029');
INSERT INTO preferences (id, nim, swap_course) VALUES (41, 'MHS16_041', 41);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 1, 100, 'CLS005');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (41, 2, 90, 'CLS001');
INSERT INTO preferences (id, nim, swap_course) VALUES (42, 'MHS16_042', 42);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 1, 100, 'CLS023');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (42, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (43, 'MHS16_043', 43);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 1, 100, 'CLS014');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (43, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (44, 'MHS16_044', 44);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 1, 100, 'CLS039');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (44, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (45, 'MHS16_045', 45);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 1, 100, 'CLS034');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (45, 2, 90, 'CLS003');
INSERT INTO preferences (id, nim, swap_course) VALUES (46, 'MHS16_046', 46);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (46, 2, 90, 'CLS017');
INSERT INTO preferences (id, nim, swap_course) VALUES (47, 'MHS16_047', 47);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 1, 100, 'CLS035');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (47, 2, 90, 'CLS010');
INSERT INTO preferences (id, nim, swap_course) VALUES (48, 'MHS16_048', 48);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (48, 2, 90, 'CLS048');
INSERT INTO preferences (id, nim, swap_course) VALUES (49, 'MHS16_049', 49);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (49, 2, 90, 'CLS011');
INSERT INTO preferences (id, nim, swap_course) VALUES (50, 'MHS16_050', 50);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 1, 100, 'CLS010');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (50, 2, 90, 'CLS033');
INSERT INTO preferences (id, nim, swap_course) VALUES (51, 'MHS16_051', 51);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 1, 100, 'CLS032');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (51, 2, 90, 'CLS042');
INSERT INTO preferences (id, nim, swap_course) VALUES (52, 'MHS16_052', 52);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 1, 100, 'CLS043');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (52, 2, 90, 'CLS026');
INSERT INTO preferences (id, nim, swap_course) VALUES (53, 'MHS16_053', 53);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (53, 2, 90, 'CLS002');
INSERT INTO preferences (id, nim, swap_course) VALUES (54, 'MHS16_054', 54);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 1, 100, 'CLS027');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (54, 2, 90, 'CLS050');
INSERT INTO preferences (id, nim, swap_course) VALUES (55, 'MHS16_055', 55);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 1, 100, 'CLS040');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (55, 2, 90, 'CLS005');
INSERT INTO preferences (id, nim, swap_course) VALUES (56, 'MHS16_056', 56);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (56, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (57, 'MHS16_057', 57);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 1, 100, 'CLS025');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (57, 2, 90, 'CLS018');
INSERT INTO preferences (id, nim, swap_course) VALUES (58, 'MHS16_058', 58);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 1, 100, 'CLS044');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (58, 2, 90, 'CLS043');
INSERT INTO preferences (id, nim, swap_course) VALUES (59, 'MHS16_059', 59);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (59, 2, 90, 'CLS025');
INSERT INTO preferences (id, nim, swap_course) VALUES (60, 'MHS16_060', 60);
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 1, 100, 'CLS050');
INSERT INTO pref_courses (preference_id, urutan, skor, group_code) VALUES (60, 2, 90, 'CLS033');


